# Generated by Django 5.1.7 on 2025-03-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Records',
            new_name='User_Record',
        ),
    ]
