# Generated by Django 5.1.7 on 2025-03-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilerapp', '0003_user_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_record',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpeg', null=True, upload_to='profile_pics/'),
        ),
    ]
